[project]
name = "tp"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "numpy>=2.2.6",
    "opencv-python>=4.11.0.86",
    "scipy>=1.15.3",
    "tqdm>=4.67.1",
]
